CREATE TABLE [dbo].[SAMOCHODY]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [MARKA] NTEXT NOT NULL, 
    [MODEL] NTEXT NOT NULL, 
    [SILNIK] NTEXT NULL, 
    [VIN] TEXT NULL, 
    [LINK] TEXT NOT NULL, 
    [SCIEZKA] TEXT NULL, 
    [CENA] DECIMAL NULL, 
    [STAN] NCHAR(10) NULL
)
